exports.config={
    "showTime":false,
    "showWatcherNum":true,
    "showUserName":true,
    "showWelcome":true,
    "notify":true,
    "reconnect":false,
    "save":false,
    "mpv":true
};
exports.liveroom={
    "roomid":"5269"
};
